### ISSUE TITLE
Failed tests being reported as skipped

### ISSUE THREAD

**Issue by kappa10j** [wswebcreation/multiple-cucumber-html-reporter#45]
It seems that when a test has failed at the before function, the reporter reports it as skipped.

**Comment by wswebcreation** [comment]
Hi @kappa10j 

Can you please provide more info? Can you give an example json where this happens? Then I can verify it and fix it.

Tnx in advance

**Comment by kappa10j** [comment]
Hi,

I can't provide an example as I'm working within a firm that disallows
posting.  But if you were to execute a test with multiple steps where an
err is thrown or a chai.assert.fail() in a Before() function, then any
Given, When, or Then steps will be skipped.  The before will have failed
and he json results file will show this, but the reporter won't.

thanks

**Comment by Brian-Dawson-Nerdery** [comment]
I would expect it to be handled that way. Before is meant to be setup for a test, if the setup fails, then the requirements have not been met to run the test. If you're using Before, you're telling it "xyz needs to happen in order to run the test". The test didn't fail, the setup did, so it doesn't make sense to fail the test when it never ran.

**Comment by wswebcreation** [comment]
I've checked it with this data

```js
[
  {
    "keyword": "Feature",
    "line": 1,
    "name": "Before hook failure",
    "tags": [],
    "uri": "/Users/wswebcreation/multiple-cucumber-html-report/e2e/features/before-failure.feature",
    "elements": [
      {
        "keyword": "Scenario",
        "line": 14,
        "name": "I want a before hook to fail to check the report",
        "tags": [
          {
            "line": 13,
            "name": "@before"
          }
        ],
        "id": "before-failure;i-want-a-before-hook-to-fail-to-check-the-report",
        "steps": [
          {
            "arguments": [],
            "keyword": "Before",
            "result": {
              "status": "failed",
              "duration": 5,
              "error_message": "Error: fail\n    at World.<anonymous> (/Users/wswebcreation/multiple-cucumber-html-report/e2e/config/helpers/before.scenario.js:27:32)\n    at new Promise (<anonymous>)\n    at new F (/Users/wswebcreation/multiple-cucumber-html-report/node_modules/wdio-sync/node_modules/core-js/library/modules/_export.js:36:28)"
            },
            "hidden": true,
            "match": {
              "location": "/Users/wswebcreation/multiple-cucumber-html-report/node_modules/cucumber/lib/index.js:176"
            }
          },
          {
            "arguments": [],
            "keyword": "Given ",
            "name": "I have foo",
            "result": {
              "status": "skipped"
            },
            "isBackground": true,
            "line": 4,
            "match": {
              "location": "/Users/wswebcreation/multiple-cucumber-html-report/node_modules/cucumber/lib/index.js:176"
            }
          },
          {
            "arguments": [],
            "keyword": "And ",
            "name": "I add bar",
            "result": {
              "status": "skipped"
            },
            "isBackground": true,
            "line": 5,
            "match": {
              "location": "/Users/wswebcreation/multiple-cucumber-html-report/node_modules/cucumber/lib/index.js:176"
            }
          },
          {
            "arguments": [],
            "keyword": "Then ",
            "name": "I have foo-bar",
            "result": {
              "status": "skipped"
            },
            "isBackground": true,
            "line": 6,
            "match": {
              "location": "/Users/wswebcreation/multiple-cucumber-html-report/node_modules/cucumber/lib/index.js:176"
            }
          },
          {
            "arguments": [],
            "keyword": "After",
            "result": {
              "status": "passed",
              "duration": 0
            },
            "hidden": true,
            "match": {
              "location": "/Users/wswebcreation/multiple-cucumber-html-report/node_modules/cucumber/lib/index.js:176"
            }
          }
        ]
      }
    ],
    "id": "before-failure",
    "metadata": {
      "app": {
        "name": "FailureApp",
        "version": "1.0.1"
      },
      "device": "iPhone 8",
      "platform": {
        "name": "iOS",
        "version": "11.3"
      }
    }
  }
]
```

**Report overview:**
![image](https://user-images.githubusercontent.com/11979740/39461042-8b557880-4d08-11e8-950e-610de8a57688.png)

**Feature details:**
![image](https://user-images.githubusercontent.com/11979740/39461050-94afcec6-4d08-11e8-9dd9-15479ec408f3.png)

@kappa10j What do you expect for a result, because this is what the console is also showing

![image](https://user-images.githubusercontent.com/11979740/39461194-4b986558-4d09-11e8-961f-88655018bb9e.png)

and I do agree with what @Brian-Dawson-Nerdery is explaining

**Comment by wswebcreation** [comment]
@kappa10j 

Can you please please explain what you expect and see where the report is wrong? Otherwise I'm going to close this after the weekend.

**Comment by wswebcreation** [comment]
Going to close it due to inactivity
