### ISSUE TITLE
report failed to generate on big json

### ISSUE THREAD

**Issue by muthukumarse** [wswebcreation/multiple-cucumber-html-reporter#72]
$ rimraf st-coverage && node reports/generate.js
lodash.templateSources[8]:244
((__t = ( step.image[i] )) == null ? '' : __t) +
                                               ^

RangeError: Invalid string length
    at eval (lodash.templateSources[8]:244:48)
    at arrayEach (/Users/muthu/Documents/office/workspace/ui-st-automation/node_modules/multiple-cucumber-html-reporter/node_modules/lodash/lodash.js:508:11)
    at Function.forEach (/Users/muthu/Documents/office/workspace/ui-st-automation/node_modules/multiple-cucumber-html-reporter/node_modules/lodash/lodash.js:9334:14)
    at eval (lodash.templateSources[8]:78:4)
    at arrayEach (/Users/muthu/Documents/office/workspace/ui-st-automation/node_modules/multiple-cucumber-html-reporter/node_modules/lodash/lodash.js:508:11)
    at Function.forEach (/Users/muthu/Documents/office/workspace/ui-st-automation/node_modules/multiple-cucumber-html-reporter/node_modules/lodash/lodash.js:9334:14)
    at eval (lodash.templateSources[8]:10:4)
    at suite.features.forEach.feature (/Users/muthu/Documents/office/workspace/ui-st-automation/node_modules/multiple-cucumber-html-reporter/lib/generate-report.js:505:78)
    at Array.forEach (<anonymous>)
    at _createFeatureIndexPages (/Users/muthu/Documents/office/workspace/ui-st-automation/node_modules/multiple-cucumber-html-reporter/lib/generate-report.js:487:20)

Do you recognize this issue?

**Comment by muthukumarse** [comment]
@wswebcreation 
debugged and found the issue.

when the image data string is too big and trying to put that in href below code causing this issue.

https://github.com/wswebcreation/multiple-cucumber-html-reporter/blob/023a1ada2713b5a4b54eca0c6c0229691cba572b/templates/components/scenarios.tmpl#L204

if i remove the <a class="screenshot" href="<%= step.image[i] %>" target="_blank"> . line its working fine.

what you think. We should avoid putting whole image data content into href

**Comment by muthukumarse** [comment]
@wswebcreation 
I tried with window.open on img tag onclick. it doesn't work for data:image/png;base64.....
can I raise PR ? with a href removed.

user should aware how to open the image in new tab by right click in recent browsers. :)

**Comment by wswebcreation** [comment]
Just merged the PR and release `1.11.5`. Thanks for your help!

**Comment by muthukumarse** [comment]
👍
