### ISSUE TITLE
The picture on html report disappeared

### ISSUE THREAD

**Issue by fergadipa** [wswebcreation/multiple-cucumber-html-reporter#75]
**Environment (please complete the following information):**
 - multiple-cucumber-html-reporter: [1.11.4]
 - Node.js version: [v10.13.0]
 - NPM version: [6.4.1]
 - Platform name and version: [Ubuntu 18]
 - Cucucmber version: [5.0.2]

**Config of protractor + multiple-cucumber-html-reporter**
An example of how you configured the reporter in your webdriver.io config

**Describe the bug**
This happened on my Azure DevOps pipeline. When I ran command "node create-html-report-chrome.js", this error generated:
2018-12-19T03:18:15.6138772Z (node:27356) UnhandledPromiseRejectionWarning: Error: Exited with code 3
2018-12-19T03:18:15.6139151Z     at ChildProcess.cp.once.code (/home/fergad061436/myagent/_work/8/s/node_modules/opn/index.js:84:13)
2018-12-19T03:18:15.6139404Z     at Object.onceWrapper (events.js:273:13)
2018-12-19T03:18:15.6140531Z     at ChildProcess.emit (events.js:182:13)
2018-12-19T03:18:15.6141686Z > at-web-seva@1.0.0 report-chrome /home/fergad061436/myagent/_work/8/s
2018-12-19T03:18:15.6142536Z     at maybeClose (internal/child_process.js:962:16)
2018-12-19T03:18:15.6143104Z > node create-html-report-chrome.js
2018-12-19T03:18:15.6144335Z     at Socket.stream.socket.on (internal/child_process.js:381:11)
2018-12-19T03:18:15.6144398Z 
2018-12-19T03:18:15.6145375Z     at Socket.emit (events.js:182:13)
2018-12-19T03:18:15.6145443Z 
2018-12-19T03:18:15.6146338Z     at Pipe._handle.close (net.js:606:12)
2018-12-19T03:18:15.6146400Z 
2018-12-19T03:18:15.6161341Z (node:27356) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2018-12-19T03:18:15.6161501Z =====================================================================================
2018-12-19T03:18:15.6165951Z (node:27356) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2018-12-19T03:18:15.6166109Z     Multiple Cucumber HTML report generated in:
2018-12-19T03:18:15.6166305Z 
2018-12-19T03:18:15.6166824Z     /home/fergad061436/myagent/_work/8/s/reports/index.html
2018-12-19T03:18:15.6167104Z =====================================================================================

And the impact will be like this:
https://ibb.co/BGHHrKq

**To Reproduce**
Run command "node create-html-report-chrome.js"
Open the html report

**Expected behavior**
The html report will be generated properly.

**Log**
2018-12-19T03:18:15.6138772Z (node:27356) UnhandledPromiseRejectionWarning: Error: Exited with code 3
2018-12-19T03:18:15.6139151Z     at ChildProcess.cp.once.code (/home/fergad061436/myagent/_work/8/s/node_modules/opn/index.js:84:13)
2018-12-19T03:18:15.6139404Z     at Object.onceWrapper (events.js:273:13)
2018-12-19T03:18:15.6140531Z     at ChildProcess.emit (events.js:182:13)
2018-12-19T03:18:15.6141686Z > at-web-seva@1.0.0 report-chrome /home/fergad061436/myagent/_work/8/s
2018-12-19T03:18:15.6142536Z     at maybeClose (internal/child_process.js:962:16)
2018-12-19T03:18:15.6143104Z > node create-html-report-chrome.js
2018-12-19T03:18:15.6144335Z     at Socket.stream.socket.on (internal/child_process.js:381:11)
2018-12-19T03:18:15.6144398Z 
2018-12-19T03:18:15.6145375Z     at Socket.emit (events.js:182:13)
2018-12-19T03:18:15.6145443Z 
2018-12-19T03:18:15.6146338Z     at Pipe._handle.close (net.js:606:12)
2018-12-19T03:18:15.6146400Z 
2018-12-19T03:18:15.6161341Z (node:27356) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2018-12-19T03:18:15.6161501Z =====================================================================================
2018-12-19T03:18:15.6165951Z (node:27356) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2018-12-19T03:18:15.6166109Z     Multiple Cucumber HTML report generated in:
2018-12-19T03:18:15.6166305Z 
2018-12-19T03:18:15.6166824Z     /home/fergad061436/myagent/_work/8/s/reports/index.html
2018-12-19T03:18:15.6167104Z =====================================================================================

**Comment by fergadipa** [comment]
I got the cause of this issue. Thanks @wswebcreation

**Comment by wswebcreation** [comment]
Hi @fergadipa 

Thanks for closing it. Can you also share the cause?
