### ISSUE TITLE
Error on file lock when multiple instances are running parallel

### ISSUE THREAD

**Issue by Doschdn1** [wswebcreation/multiple-cucumber-html-reporter#79]
Hello,

we having a Problem since some weeks. We updated some of our node-modules recently and since then we're getting some errors when the report is created.
We are running multiple instances parallel. We think the problem is, when two or more instances are trying to create the report nearly at the same time:

```shell
[chrome #01-118] [08:41:46] I/plugins - [31m 	 Fail:  protractor-multiple-cucumber-html-reporter-plugin Runtime [39m
[chrome #01-118] [08:41:46] E/plugins - 		Failure during postResults: EBUSY: resource busy or locked, unlink 'C:\dev\clientapplication\e2e\reports\assets\fonts\fontawesome-webfont.woff'
[chrome #01-118] [08:41:46] E/plugins - 		Error: EBUSY: resource busy or locked, unlink 'C:\dev\clientapplication\e2e\reports\assets\fonts\fontawesome-webfont.woff'
[chrome #01-118] 		    at Object.unlinkSync (fs.js:949:3)
[chrome #01-118] 		    at mayCopyFile (C:\dev\clientapplication\node_modules\multiple-cucumber-html-reporter\node_modules\fs-extra\lib\copy-sync\copy-sync.js:69:8)
[chrome #01-118] 		    at onFile (C:\dev\clientapplication\node_modules\multiple-cucumber-html-reporter\node_modules\fs-extra\lib\copy-sync\copy-sync.js:60:12)
[chrome #01-118] 		    at getStats (C:\dev\clientapplication\node_modules\multiple-cucumber-html-reporter\node_modules\fs-extra\lib\copy-sync\copy-sync.js:51:39)



[chrome #01-118] 		    at startCopy (C:\dev\clientapplication\node_modules\multiple-cucumber-html-reporter\node_modules\fs-extra\lib\copy-sync\copy-sync.js:41:10)
[chrome #01-118] 		    at fs.readdirSync.forEach.item (C:\dev\clientapplication\node_modules\multiple-cucumber-html-reporter\node_modules\fs-extra\lib\copy-sync\copy-sync.js:142:5)
[chrome #01-118] 		    at Array.forEach (<anonymous>)
[chrome #01-118] 		    at copyDir (C:\dev\clientapplication\node_modules\multiple-cucumber-html-reporter\node_modules\fs-extra\lib\copy-sync\copy-sync.js:141:23)
[chrome #01-118] 		    at mayCopyDir (C:\dev\clientapplication\node_modules\multiple-cucumber-html-reporter\node_modules\fs-extra\lib\copy-sync\copy-sync.js:131:10)
[chrome #01-118] 		    at onDir (C:\dev\clientapplication\node_modules\multiple-cucumber-html-reporter\node_modules\fs-extra\lib\copy-sync\copy-sync.js:120:12)
[chrome #01-118] 		    at getStats (C:\dev\clientapplication\node_modules\multiple-cucumber-html-reporter\node_modules\fs-extra\lib\copy-sync\copy-sync.js:48:32)
[chrome #01-118] 		    at startCopy (C:\dev\clientapplication\node_modules\multiple-cucumber-html-reporter\node_modules\fs-extra\lib\copy-sync\copy-sync.js:41:10)
[chrome #01-118] 		    at fs.readdirSync.forEach.item (C:\dev\clientapplication\node_modules\multiple-cucumber-html-reporter\node_modules\fs-extra\lib\copy-sync\copy-sync.js:142:5)
[chrome #01-118] 		    at Array.forEach (<anonymous>)
[chrome #01-118] 		    at copyDir (C:\dev\clientapplication\node_modules\multiple-cucumber-html-reporter\node_modules\fs-extra\lib\copy-sync\copy-sync.js:141:23)
[chrome #01-118] 		    at mayCopyDir (C:\dev\clientapplication\node_modules\multiple-cucumber-html-reporter\node_modules\fs-extra\lib\copy-sync\copy-sync.js:131:10)
```

**Comment by wswebcreation** [comment]
Hi @Doschdn1 

Can you please fill out the template when you submit a bug. It's now harder for me to verify this issue.

**Comment by dannycohn** [comment]
Any movement on this? I am experiencing the same issue.

**Comment by wswebcreation** [comment]
@Doschdn1 and @dannycohn 

First of all this is cause by the https://github.com/wswebcreation/protractor-multiple-cucumber-html-reporter-plugin module and not with this module.

Secondly the architecture of Protractor Plugins is that it will will be called for each instance (read capability) in your config. This means that when an instance is done running, it will generate the report for you. This could mean in some situations the report is generated and at the same time a new report is generated locking the files.

There is no beforeLaunch and onComplete hook available within the plugin architecture that might be able to do that.

Maybe there is a way to not write files if the exists, might be a good option for a PR 😉

**Comment by wswebcreation** [comment]
I just created a small fix for `multiple-cucumber-html-reporter` and release a fix version for https://github.com/wswebcreation/protractor-multiple-cucumber-html-reporter-plugin/releases/tag/v1.8.1.

I'm going to close this for now because it should not happen with the latest version anymore
